import logging

import flet as ft

from components.user_menu import UserAvatar
from constants.breakpoints import Breakpoints
from constants.dimensions import Dimensions
from constants.navigation import NavID
from constants.spacing import Spacing
from constants.typography import FontSize
from contexts.room import RoomContext

logger = logging.getLogger(__name__)


@ft.component
def RoomShell() -> ft.Control:
	room = ft.use_context(RoomContext)
	logger.info(room.room_id)

	width, set_width = ft.use_state(ft.context.page.width or 0)
	expanded, set_expanded = ft.use_state(False)

	def on_resize(_):
		set_width(ft.context.page.width or 0)

	ft.context.page.on_resize = on_resize

	is_large = width >= Breakpoints.LG
	is_medium = width >= Breakpoints.MD and width < Breakpoints.LG

	def sidebar(*, dismissible: bool) -> ft.Control:
		return ft.Container(
			width=Dimensions.SIDEBAR_WIDTH,
			padding=Spacing.MD,
			content=ft.Column(
				spacing=Spacing.SM,
				expand=True,
				controls=[
					*(
						[
							ft.IconButton(
								flip=ft.Flip(flip_x=True),
								icon=ft.Icons.MENU_OPEN,
								tooltip="Close navigation",
								on_click=lambda _: set_expanded(False),
							)
						]
						if dismissible
						else []
					),
					ft.TextButton(
						width=float("inf"),
						icon=ft.Icons.CHAT,
						content="Chat",
						on_click=None,
						style=ft.ButtonStyle(
							padding=ft.Padding.symmetric(
								horizontal=Spacing.MD,
								vertical=Spacing.LG,
							),
							alignment=ft.Alignment.CENTER_LEFT,
							shape=ft.RoundedRectangleBorder(radius=12),
						),
					),
					ft.TextButton(
						width=float("inf"),
						icon=ft.Icons.DRAW,
						content="Whiteboard",
						on_click=None,
						style=ft.ButtonStyle(
							padding=ft.Padding.symmetric(
								horizontal=Spacing.MD,
								vertical=Spacing.LG,
							),
							alignment=ft.Alignment.CENTER_LEFT,
							shape=ft.RoundedRectangleBorder(radius=12),
						),
					),
					ft.TextButton(
						width=float("inf"),
						icon=ft.Icons.NOTES,
						content="Notes",
						on_click=None,
						style=ft.ButtonStyle(
							padding=ft.Padding.symmetric(
								horizontal=Spacing.MD,
								vertical=Spacing.LG,
							),
							alignment=ft.Alignment.CENTER_LEFT,
							shape=ft.RoundedRectangleBorder(radius=12),
						),
					),
					ft.Divider(),
					ft.ListView(
						spacing=Spacing.SM,
						expand=True,
						controls=[
							ft.Row(
								margin=Spacing.SM,
								controls=[
									UserAvatar(),
									ft.Column(
										spacing=0,
										controls=[
											ft.Text(
												"anir183",
												size=FontSize.MD,
												weight=ft.FontWeight.W_500,
											),
											ft.Text(
												"online",
												size=FontSize.SM,
												opacity=0.7,
											),
										],
									),
								],
							),
							ft.Row(
								margin=Spacing.SM,
								controls=[
									UserAvatar(),
									ft.Column(
										spacing=0,
										controls=[
											ft.Text(
												"anir183",
												size=FontSize.MD,
												weight=ft.FontWeight.W_500,
											),
											ft.Text(
												"online",
												size=FontSize.SM,
												opacity=0.7,
											),
										],
									),
								],
							),
							ft.Row(
								margin=Spacing.SM,
								controls=[
									UserAvatar(),
									ft.Column(
										spacing=0,
										controls=[
											ft.Text(
												"anir183",
												size=FontSize.MD,
												weight=ft.FontWeight.W_500,
											),
											ft.Text(
												"online",
												size=FontSize.SM,
												opacity=0.7,
											),
										],
									),
								],
							),
							ft.Row(
								margin=Spacing.SM,
								controls=[
									UserAvatar(),
									ft.Column(
										spacing=0,
										controls=[
											ft.Text(
												"anir183",
												size=FontSize.MD,
												weight=ft.FontWeight.W_500,
											),
											ft.Text(
												"online",
												size=FontSize.SM,
												opacity=0.7,
											),
										],
									),
								],
							),
							ft.Row(
								margin=Spacing.SM,
								controls=[
									UserAvatar(),
									ft.Column(
										spacing=0,
										controls=[
											ft.Text(
												"anir183",
												size=FontSize.MD,
												weight=ft.FontWeight.W_500,
											),
											ft.Text(
												"online",
												size=FontSize.SM,
												opacity=0.7,
											),
										],
									),
								],
							),
							ft.Row(
								margin=Spacing.SM,
								controls=[
									UserAvatar(),
									ft.Column(
										spacing=0,
										controls=[
											ft.Text(
												"anir183",
												size=FontSize.MD,
												weight=ft.FontWeight.W_500,
											),
											ft.Text(
												"online",
												size=FontSize.SM,
												opacity=0.7,
											),
										],
									),
								],
							),
						],
					),
				],
			),
		)

	if is_large:
		return ft.Row(
			expand=True,
			controls=[
				ft.Container(
					expand=True,
					content=ft.Placeholder(),
				),
				ft.VerticalDivider(width=1),
				sidebar(dismissible=False),
			],
		)
	elif is_medium and expanded:
		return ft.Row(
			expand=True,
			controls=[
				ft.Container(
					expand=True,
					content=ft.Placeholder(),
				),
				ft.VerticalDivider(width=1),
				sidebar(dismissible=True),
			],
		)
	elif is_medium:
		return ft.Row(
			expand=True,
			controls=[
				ft.Container(
					expand=True,
					content=ft.Placeholder(),
				),
				ft.VerticalDivider(width=1),
				ft.Column(
					width=Dimensions.NAV_RAIL_WIDTH,
					controls=[
						ft.NavigationRail(
							selected_index=0,
							height=200,
							label_type=ft.NavigationRailLabelType.NONE,
							on_change=None,
							leading=ft.IconButton(
								icon=ft.Icons.MENU,
								tooltip="Open navigation",
								on_click=lambda _: set_expanded(True),
							),
							destinations=[
								ft.NavigationRailDestination(
									icon=ft.Icons.CHAT_OUTLINED,
									selected_icon=ft.Icons.CHAT,
									tooltip="Chat",
									label="Chat",
								),
								ft.NavigationRailDestination(
									icon=ft.Icons.DRAW_OUTLINED,
									selected_icon=ft.Icons.DRAW,
									tooltip="Whiteboard",
									label="Whiteboard",
								),
								ft.NavigationRailDestination(
									icon=ft.Icons.NOTES_OUTLINED,
									selected_icon=ft.Icons.NOTES,
									tooltip="Notes",
									label="Notes",
								),
							],
						),
						ft.Container(
							alignment=ft.Alignment.CENTER,
							content=UserAvatar(),
							padding=ft.Padding.symmetric(vertical=Spacing.XS),
						),
						ft.Container(
							alignment=ft.Alignment.CENTER,
							content=UserAvatar(),
							padding=ft.Padding.symmetric(vertical=Spacing.XS),
						),
						ft.Container(
							alignment=ft.Alignment.CENTER,
							content=UserAvatar(),
							padding=ft.Padding.symmetric(vertical=Spacing.XS),
						),
						ft.Container(
							alignment=ft.Alignment.CENTER,
							content=UserAvatar(),
							padding=ft.Padding.symmetric(vertical=Spacing.XS),
						),
						ft.Container(
							alignment=ft.Alignment.CENTER,
							content=UserAvatar(),
							padding=ft.Padding.symmetric(vertical=Spacing.XS),
						),
						ft.Container(
							alignment=ft.Alignment.CENTER,
							content=UserAvatar(),
							padding=ft.Padding.symmetric(vertical=Spacing.XS),
						),
					],
				),
			],
		)

	return ft.Column(
		spacing=Spacing.SM,
		expand=True,
		controls=[
			ft.TextButton(
				width=float("inf"),
				icon=ft.Icons.CHAT,
				content="Chat",
				on_click=None,
				style=ft.ButtonStyle(
					padding=ft.Padding.symmetric(
						horizontal=Spacing.MD,
						vertical=Spacing.LG,
					),
					alignment=ft.Alignment.CENTER_LEFT,
					shape=ft.RoundedRectangleBorder(radius=12),
				),
			),
			ft.TextButton(
				width=float("inf"),
				icon=ft.Icons.DRAW,
				content="Whiteboard",
				on_click=None,
				style=ft.ButtonStyle(
					padding=ft.Padding.symmetric(
						horizontal=Spacing.MD,
						vertical=Spacing.LG,
					),
					alignment=ft.Alignment.CENTER_LEFT,
					shape=ft.RoundedRectangleBorder(radius=12),
				),
			),
			ft.TextButton(
				width=float("inf"),
				icon=ft.Icons.NOTES,
				content="Notes",
				on_click=None,
				style=ft.ButtonStyle(
					padding=ft.Padding.symmetric(
						horizontal=Spacing.MD,
						vertical=Spacing.LG,
					),
					alignment=ft.Alignment.CENTER_LEFT,
					shape=ft.RoundedRectangleBorder(radius=12),
				),
			),
			ft.Divider(),
			ft.ListView(
				spacing=Spacing.SM,
				expand=True,
				controls=[
					ft.Row(
						margin=Spacing.SM,
						controls=[
							UserAvatar(),
							ft.Column(
								spacing=0,
								controls=[
									ft.Text(
										"anir183",
										size=FontSize.MD,
										weight=ft.FontWeight.W_500,
									),
									ft.Text(
										"online",
										size=FontSize.SM,
										opacity=0.7,
									),
								],
							),
						],
					),
					ft.Row(
						margin=Spacing.SM,
						controls=[
							UserAvatar(),
							ft.Column(
								spacing=0,
								controls=[
									ft.Text(
										"anir183",
										size=FontSize.MD,
										weight=ft.FontWeight.W_500,
									),
									ft.Text(
										"online",
										size=FontSize.SM,
										opacity=0.7,
									),
								],
							),
						],
					),
					ft.Row(
						margin=Spacing.SM,
						controls=[
							UserAvatar(),
							ft.Column(
								spacing=0,
								controls=[
									ft.Text(
										"anir183",
										size=FontSize.MD,
										weight=ft.FontWeight.W_500,
									),
									ft.Text(
										"online",
										size=FontSize.SM,
										opacity=0.7,
									),
								],
							),
						],
					),
					ft.Row(
						margin=Spacing.SM,
						controls=[
							UserAvatar(),
							ft.Column(
								spacing=0,
								controls=[
									ft.Text(
										"anir183",
										size=FontSize.MD,
										weight=ft.FontWeight.W_500,
									),
									ft.Text(
										"online",
										size=FontSize.SM,
										opacity=0.7,
									),
								],
							),
						],
					),
					ft.Row(
						margin=Spacing.SM,
						controls=[
							UserAvatar(),
							ft.Column(
								spacing=0,
								controls=[
									ft.Text(
										"anir183",
										size=FontSize.MD,
										weight=ft.FontWeight.W_500,
									),
									ft.Text(
										"online",
										size=FontSize.SM,
										opacity=0.7,
									),
								],
							),
						],
					),
					ft.Row(
						margin=Spacing.SM,
						controls=[
							UserAvatar(),
							ft.Column(
								spacing=0,
								controls=[
									ft.Text(
										"anir183",
										size=FontSize.MD,
										weight=ft.FontWeight.W_500,
									),
									ft.Text(
										"online",
										size=FontSize.SM,
										opacity=0.7,
									),
								],
							),
						],
					),
				],
			),
		],
	)
